global:
  scrape_interval: 10s
rule_files:
  - /etc/prometheus/*.rule
# A scrape configuration for running Prometheus on a Kubernetes cluster.
# This uses separate scrape configs for cluster components (i.e. API server, node)
# and services to allow each to use different authentication configs.
#
# Kubernetes labels will be added as Prometheus labels on metrics via the
# `labelmap` relabeling action.

# Scrape config for cluster components.
scrape_configs:
- job_name: slaves
  honor_labels: true
  metrics_path: /federate
  params:
    match[]:
      - '{job=~"kubernetes-nodes|event-exporter|kubernetes-pods|hierarchy-exporter"}'   # Request all container-level time series
  static_configs:
    - targets:
      - prometheus-node-0:9090
      - prometheus-node-1:9090
      - prometheus-node-2:9090
      - prometheus-node-3:9090
      - prometheus-pods:9090
