apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 32190
    port: 3000
    targetPort: 3000
  selector:
    app: grafana
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  containers:
    - name: grafana
      image: grafana/grafana
      imagePullPolicy: Always
      ports:
        - containerPort: 3000
      env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "secret"
