# apiVersion: v1
# kind: Service
# metadata:
#   name: prometheus-0
#   namespace: kube-system
# spec:
#   clusterIP: None
#   ports:
#   - name: prom
#     port: 9090
#     targetPort: 9090
#   - name: am
#     port: 9093
#     targetPort: 9093
#   selector:
#     monitoring: prometheus-0
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: prometheus
#   namespace: kube-system
# spec:
#   ports:
#   - name: prom
#     nodePort: 32100
#     port: 9090
#     targetPort: 9090
#   - name: am
#     nodePort: 32101
#     port: 9093
#     targetPort: 9093
#   selector:
#     monitoring: prometheus-0
#   type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: prometheus-0
  namespace: kube-system
spec:
  containers:
    - name: prometheus
      image: ${base}/prometheus:v0.0
      imagePullPolicy: Always
      ports:
        - containerPort: 9090
          name: web
      volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
      args:
        - "-config.file=/etc/prometheus/prometheus.yml"
        - "-storage.local.path=/prometheus"
        - "-web.console.libraries=/usr/share/prometheus/console_libraries"
        - "-web.console.templates=/usr/share/prometheus/consoles"
        - "-storage.remote.opentsdb-url=http://mytsdbcluster.default:4242"
        - "-log.level=error"
        # - "-alertmanager.url=http://localhost:9093"
        # - "-web.external-url=http://${base_url}:32100/"
    - name: alertmanager
      image: ${base}/alertmanager:v0.0
      imagePullPolicy: Always
      ports:
        - containerPort: 9093
          name: alert
      volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/alertmanager
      args:
        - "-config.file=/etc/alertmanager/alertmanager.yml"
        # - "-web.external-url=http://${base_url}:32101/"
    - name: event-exporter
      image: ${base}/event-exporter:v0.0
      imagePullPolicy: Always
      ports:
        - containerPort: 9100
          name: event
      args:
        - "--web.listen-address=:9100"
    - name: hierarchy-exporter
      image: ${base}/hierarchy-exporter:v0.0.3
      imagePullPolicy: Always
      ports:
        - containerPort: 9101
          name: hierarchy
      args:
        - "--web.listen-address=:9101"
  volumes:
    - name: prometheus-config
      configMap:
        name: prometheus-config
    - name: alertmanager-config
      configMap:
        name: alertmanager-config
